- name: k8s master init config cp
  template: src=kubeadm-config.yaml dest=/tmp/kubeadm-config.yaml
- name: k8s master init cp
  template: src=master-init.sh dest=/tmp/master-init.sh
- name: k8s master init
  shell: sh /tmp/master-init.sh
